# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://deepikachhillar.github.io/ # the base hostname & protocol for your site

# User settings
title: Deepika Chhillar
email: deepika.chhillar [at] du.edu
group: Management Department
groupweb: https://daniels.du.edu/directory/deepika-chhillar/
dept: Business Administration
deptweb: https://daniels.du.edu/
institution: University of Denver
institutionweb: https://www.du.edu/
address: 2101 S. University Blvd., Denver, CO 80208
twitter: DeepikaChhillar
github: deepikachhillar
#dblp: 
gscholar: EwBFJ68AAAAJ
# linkedin: deepika-chhillar
linkedin_username: deepika-chhillar

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 3
paginate_path: /news/page:num/
excerpt_separator: <!--more-->

# Site-wide variables
keywords: Governance of AI, organizational purpose, culture, stakeholder theory
copyright: Copyright (c) Deepika Chhillar

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate
#  - jemoji
