# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://deepikachhillar.github.io/ # the base hostname & protocol for your site

# User settings
title: Deepika Chhillar
email: deepika4@illinois.edu
group: Organizational Theory & Strategy
groupweb: https://giesbusiness.illinois.edu/profile/matthew-kraatz
dept: Business Administration
deptweb: https://giesbusiness.illinois.edu/graduate-hub/doctoral/business-administration
institution: University of Illinois, Urbana-Champaign
institutionweb: https://giesbusiness.illinois.edu/
address: 1206 S. Sixth Champaign, IL 61820
twitter: DeepikaChhillar
github: deepikachhillar
dblp: 
gscholar: EwBFJ68AAAAJ

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 3
paginate_path: /news/page:num/
excerpt_separator: <!--more-->

# Site-wide variables
keywords: organizational culture, machine learning, glassdoor, insitutional theory
copyright: Copyright (c) Deepika Chhillar

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate
#  - jemoji
